server:
  port: 0

spring:
  application:
    name: terrible-thumbnail-creator
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  cloud:
    stream:
      bindings:
        thumbnailChannel:
          destination: terrible-thumbnail-creator

logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
